import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1731080972726 implements MigrationInterface {
    name = 'Migration1731080972726'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "role" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_b36bcfe02fc8de3c57a8b2391c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "status" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" integer NOT NULL, "name" character varying NOT NULL, CONSTRAINT "PK_e12743a7086ec826733f54e1d95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "file" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "path" character varying NOT NULL, CONSTRAINT "PK_36b46d232307066b3a2c9ea3a1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "address" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "country" character varying NOT NULL, "city" character varying NOT NULL, "longitude" double precision NOT NULL, "latitude" double precision NOT NULL, "country_flag" character varying, "street" character varying NOT NULL, CONSTRAINT "PK_d92de1f82754668b5f5f5dd4fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "name" character varying NOT NULL, "bio" character varying NOT NULL, "description" character varying NOT NULL, "store_unique_code" character varying NOT NULL, "active" boolean NOT NULL DEFAULT true, "image_id" uuid, "address_id" integer, CONSTRAINT "UQ_22fbc81f50d2296ffe1ce2506c6" UNIQUE ("store_unique_code"), CONSTRAINT "REL_36605697bf2bb48490037ca84f" UNIQUE ("image_id"), CONSTRAINT "REL_f3eb3afc763da3076e80e2459d" UNIQUE ("address_id"), CONSTRAINT "PK_f3172007d4de5ae8e7692759d79" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "store_admin" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "admin_type" character varying NOT NULL DEFAULT 'ADMIN', "store_id" integer, "tenant_id" integer, CONSTRAINT "PK_30b9f4a4d383b7e067b39a29eaf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "category" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "name" character varying NOT NULL, "image_id" uuid, CONSTRAINT "REL_dc252738f70366595ac88f5a98" UNIQUE ("image_id"), CONSTRAINT "PK_9c4e4a89e3674fc9f382d733f03" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."product_type_enum" AS ENUM('DONATIONS', 'SWAPS', 'PURCHASES')`);
        await queryRunner.query(`CREATE TABLE "product" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "name" character varying NOT NULL, "stock" integer NOT NULL DEFAULT '0', "price" integer NOT NULL DEFAULT '0', "description" character varying, "type" "public"."product_type_enum" NOT NULL DEFAULT 'PURCHASES', "brand" character varying, "modal" character varying, "size" integer NOT NULL DEFAULT '0', "category_id" integer NOT NULL, CONSTRAINT "PK_bebc9158e480b949565b4dc7a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applicant_to_donation" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying NOT NULL DEFAULT 'PENDING', "donation_id" integer, "applicant_id" integer, CONSTRAINT "PK_96912d97643cc9155a49bd50325" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "donation" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "description" character varying NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "active" boolean NOT NULL DEFAULT true, "creator_id" integer, "address_id" integer NOT NULL, "product_id" integer NOT NULL, CONSTRAINT "REL_8e8c4837ff3e7700e596d2ef1b" UNIQUE ("address_id"), CONSTRAINT "REL_a3a5dc0ed1d8185a33d9ee4d5f" UNIQUE ("product_id"), CONSTRAINT "PK_25fb5a541964bc5cfc18fb13a82" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applicant_to_swap" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "quantity" integer NOT NULL DEFAULT '1', "status" character varying NOT NULL DEFAULT 'PENDING', "swap_id" integer, "product_id" integer NOT NULL, "applicant_id" integer, CONSTRAINT "REL_6e2335e86fd252ad558da9bae3" UNIQUE ("product_id"), CONSTRAINT "PK_be29224de8856caadd70aec2c58" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "swap" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "description" character varying NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "active" boolean NOT NULL DEFAULT true, "creator_id" integer, "address_id" integer NOT NULL, "product_id" integer, CONSTRAINT "REL_70262b53eded9704d98d5a87c7" UNIQUE ("address_id"), CONSTRAINT "REL_fb2b544194e1d35c4fe79f81b7" UNIQUE ("product_id"), CONSTRAINT "PK_4a10d0f359339acef77e7f986d9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "community" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "name" character varying NOT NULL, "bio" character varying NOT NULL, "is_private" boolean NOT NULL DEFAULT false, "invitation_code" character varying NOT NULL, "creator_id" integer, "image_id" uuid, CONSTRAINT "REL_f45517568a62724d6c1c44e6b6" UNIQUE ("image_id"), CONSTRAINT "PK_cae794115a383328e8923de4193" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "applicant_to_community" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" character varying NOT NULL DEFAULT 'PENDING', "community_id" integer, "subscriber_id" integer, CONSTRAINT "PK_cd8f2fb6016bd569b0fa02d2f78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying, "provider" character varying NOT NULL DEFAULT 'email', "social_id" character varying, "first_name" character varying, "last_name" character varying, "phone" character varying, "deleted_at" TIMESTAMP, "notifications_token" character varying, "is_new_user" boolean NOT NULL DEFAULT true, "photo_id" uuid, "role_id" integer, "status_id" integer, "address_id" integer, CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "UQ_8e1f623798118e629b46a9e6299" UNIQUE ("phone"), CONSTRAINT "REL_302d96673413455481d5ff4022" UNIQUE ("address_id"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0cd76a8cdee62eeff31d384b73" ON "user" ("social_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8e1f623798118e629b46a9e629" ON "user" ("phone") `);
        await queryRunner.query(`CREATE TABLE "testimonial" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "comment" character varying NOT NULL, "rate" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_e1aee1c726db2d336480c69f7cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "session" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "hash" character varying NOT NULL, "deleted_at" TIMESTAMP, "user_id" integer, CONSTRAINT "PK_f55da76ac1c3ac420f444d2ff11" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_30e98e8746699fb9af235410af" ON "session" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "search_history" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "brand" character varying, "model" character varying, "color" character varying, "reference_number" character varying, "image_url" character varying NOT NULL, "user_id" integer, CONSTRAINT "PK_cb93c8f85dbdca85943ca494812" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "otp" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "expire_in" bigint NOT NULL, "otp" character varying NOT NULL, CONSTRAINT "PK_32556d9d7b22031d7d0e1fd6723" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notification" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "title" character varying(64) NOT NULL, "message" character varying, "for_all_users" boolean NOT NULL, "type_of_sending" character varying NOT NULL DEFAULT 'IMMEDIATELY', "punctual_send_date" TIMESTAMP, "scheduled_notification" TIMESTAMP array, "active" boolean NOT NULL DEFAULT true, "is_notification_sent" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "community_feed" ("created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" character varying NOT NULL, "url" character varying NOT NULL, "creator_id" integer, "community_id" integer, CONSTRAINT "PK_05a0a8abc100e50072d3587bee9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_image_file" ("product_id" integer NOT NULL, "file_id" uuid NOT NULL, CONSTRAINT "PK_1d2a982a5f47afabaea5dd441c6" PRIMARY KEY ("product_id", "file_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4a59b6d136c6e7eaf61f22f3f4" ON "product_image_file" ("product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_223ffd0c23037df1f55ecb182a" ON "product_image_file" ("file_id") `);
        await queryRunner.query(`CREATE TABLE "notification_users_user" ("notification_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_1ec4cd1643e57ea2ffea7473b43" PRIMARY KEY ("notification_id", "user_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_68fa2627eaeda368f495765bb3" ON "notification_users_user" ("notification_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c9d92baba7161372d3d61546e" ON "notification_users_user" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "community_feed_image_file" ("community_feed_id" integer NOT NULL, "file_id" uuid NOT NULL, CONSTRAINT "PK_eab2541a0d8a9b03a35dde59645" PRIMARY KEY ("community_feed_id", "file_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6f6b3bf9a7a89c6c4cdee267c0" ON "community_feed_image_file" ("community_feed_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a4e465e0706f17aa08ebbf002" ON "community_feed_image_file" ("file_id") `);
        await queryRunner.query(`ALTER TABLE "store" ADD CONSTRAINT "FK_36605697bf2bb48490037ca84f5" FOREIGN KEY ("image_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store" ADD CONSTRAINT "FK_f3eb3afc763da3076e80e2459dd" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_admin" ADD CONSTRAINT "FK_718d4f5da12f0c830e6029a8b23" FOREIGN KEY ("store_id") REFERENCES "store"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "store_admin" ADD CONSTRAINT "FK_2b5e671b4f35cf8607999a45858" FOREIGN KEY ("tenant_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "category" ADD CONSTRAINT "FK_dc252738f70366595ac88f5a98f" FOREIGN KEY ("image_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product" ADD CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1" FOREIGN KEY ("category_id") REFERENCES "category"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_to_donation" ADD CONSTRAINT "FK_30ae4047364d83c2a783a3f077f" FOREIGN KEY ("donation_id") REFERENCES "donation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_to_donation" ADD CONSTRAINT "FK_306dd6013fc34033250219a502b" FOREIGN KEY ("applicant_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation" ADD CONSTRAINT "FK_be6b340c20f2d5eb406fc5111af" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation" ADD CONSTRAINT "FK_8e8c4837ff3e7700e596d2ef1bd" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "donation" ADD CONSTRAINT "FK_a3a5dc0ed1d8185a33d9ee4d5f0" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_to_swap" ADD CONSTRAINT "FK_88383d77582bd428bba1b6472a7" FOREIGN KEY ("swap_id") REFERENCES "swap"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_to_swap" ADD CONSTRAINT "FK_6e2335e86fd252ad558da9bae36" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_to_swap" ADD CONSTRAINT "FK_428b77efdf895328d00ba90071f" FOREIGN KEY ("applicant_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_016ee8e85157cce1e8333c59268" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_70262b53eded9704d98d5a87c73" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "swap" ADD CONSTRAINT "FK_fb2b544194e1d35c4fe79f81b7d" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community" ADD CONSTRAINT "FK_b1bfddcbe2d4c038808d3bbad58" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community" ADD CONSTRAINT "FK_f45517568a62724d6c1c44e6b66" FOREIGN KEY ("image_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_to_community" ADD CONSTRAINT "FK_4f598e7138803f4ee261ad7993c" FOREIGN KEY ("community_id") REFERENCES "community"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "applicant_to_community" ADD CONSTRAINT "FK_27fe2b73a1a9592741bc9c5116c" FOREIGN KEY ("subscriber_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_2863d588f4efce8bf42c9c63526" FOREIGN KEY ("photo_id") REFERENCES "file"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561" FOREIGN KEY ("role_id") REFERENCES "role"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_892a2061d6a04a7e2efe4c26d6f" FOREIGN KEY ("status_id") REFERENCES "status"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_302d96673413455481d5ff4022a" FOREIGN KEY ("address_id") REFERENCES "address"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "testimonial" ADD CONSTRAINT "FK_c7fc9e9b41b59e495c82ab33890" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "session" ADD CONSTRAINT "FK_30e98e8746699fb9af235410aff" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "search_history" ADD CONSTRAINT "FK_d1ebf4101b2804213251e0a04d2" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community_feed" ADD CONSTRAINT "FK_226e488ff1cdaed6666085c2238" FOREIGN KEY ("creator_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "community_feed" ADD CONSTRAINT "FK_cfdc2d5be0d75c50b484999750e" FOREIGN KEY ("community_id") REFERENCES "community"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_image_file" ADD CONSTRAINT "FK_4a59b6d136c6e7eaf61f22f3f4d" FOREIGN KEY ("product_id") REFERENCES "product"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "product_image_file" ADD CONSTRAINT "FK_223ffd0c23037df1f55ecb182ae" FOREIGN KEY ("file_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_users_user" ADD CONSTRAINT "FK_68fa2627eaeda368f495765bb38" FOREIGN KEY ("notification_id") REFERENCES "notification"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "notification_users_user" ADD CONSTRAINT "FK_8c9d92baba7161372d3d61546ec" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "community_feed_image_file" ADD CONSTRAINT "FK_6f6b3bf9a7a89c6c4cdee267c09" FOREIGN KEY ("community_feed_id") REFERENCES "community_feed"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "community_feed_image_file" ADD CONSTRAINT "FK_7a4e465e0706f17aa08ebbf002e" FOREIGN KEY ("file_id") REFERENCES "file"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "community_feed_image_file" DROP CONSTRAINT "FK_7a4e465e0706f17aa08ebbf002e"`);
        await queryRunner.query(`ALTER TABLE "community_feed_image_file" DROP CONSTRAINT "FK_6f6b3bf9a7a89c6c4cdee267c09"`);
        await queryRunner.query(`ALTER TABLE "notification_users_user" DROP CONSTRAINT "FK_8c9d92baba7161372d3d61546ec"`);
        await queryRunner.query(`ALTER TABLE "notification_users_user" DROP CONSTRAINT "FK_68fa2627eaeda368f495765bb38"`);
        await queryRunner.query(`ALTER TABLE "product_image_file" DROP CONSTRAINT "FK_223ffd0c23037df1f55ecb182ae"`);
        await queryRunner.query(`ALTER TABLE "product_image_file" DROP CONSTRAINT "FK_4a59b6d136c6e7eaf61f22f3f4d"`);
        await queryRunner.query(`ALTER TABLE "community_feed" DROP CONSTRAINT "FK_cfdc2d5be0d75c50b484999750e"`);
        await queryRunner.query(`ALTER TABLE "community_feed" DROP CONSTRAINT "FK_226e488ff1cdaed6666085c2238"`);
        await queryRunner.query(`ALTER TABLE "search_history" DROP CONSTRAINT "FK_d1ebf4101b2804213251e0a04d2"`);
        await queryRunner.query(`ALTER TABLE "session" DROP CONSTRAINT "FK_30e98e8746699fb9af235410aff"`);
        await queryRunner.query(`ALTER TABLE "testimonial" DROP CONSTRAINT "FK_c7fc9e9b41b59e495c82ab33890"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_302d96673413455481d5ff4022a"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_892a2061d6a04a7e2efe4c26d6f"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_fb2e442d14add3cefbdf33c4561"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_2863d588f4efce8bf42c9c63526"`);
        await queryRunner.query(`ALTER TABLE "applicant_to_community" DROP CONSTRAINT "FK_27fe2b73a1a9592741bc9c5116c"`);
        await queryRunner.query(`ALTER TABLE "applicant_to_community" DROP CONSTRAINT "FK_4f598e7138803f4ee261ad7993c"`);
        await queryRunner.query(`ALTER TABLE "community" DROP CONSTRAINT "FK_f45517568a62724d6c1c44e6b66"`);
        await queryRunner.query(`ALTER TABLE "community" DROP CONSTRAINT "FK_b1bfddcbe2d4c038808d3bbad58"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_fb2b544194e1d35c4fe79f81b7d"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_70262b53eded9704d98d5a87c73"`);
        await queryRunner.query(`ALTER TABLE "swap" DROP CONSTRAINT "FK_016ee8e85157cce1e8333c59268"`);
        await queryRunner.query(`ALTER TABLE "applicant_to_swap" DROP CONSTRAINT "FK_428b77efdf895328d00ba90071f"`);
        await queryRunner.query(`ALTER TABLE "applicant_to_swap" DROP CONSTRAINT "FK_6e2335e86fd252ad558da9bae36"`);
        await queryRunner.query(`ALTER TABLE "applicant_to_swap" DROP CONSTRAINT "FK_88383d77582bd428bba1b6472a7"`);
        await queryRunner.query(`ALTER TABLE "donation" DROP CONSTRAINT "FK_a3a5dc0ed1d8185a33d9ee4d5f0"`);
        await queryRunner.query(`ALTER TABLE "donation" DROP CONSTRAINT "FK_8e8c4837ff3e7700e596d2ef1bd"`);
        await queryRunner.query(`ALTER TABLE "donation" DROP CONSTRAINT "FK_be6b340c20f2d5eb406fc5111af"`);
        await queryRunner.query(`ALTER TABLE "applicant_to_donation" DROP CONSTRAINT "FK_306dd6013fc34033250219a502b"`);
        await queryRunner.query(`ALTER TABLE "applicant_to_donation" DROP CONSTRAINT "FK_30ae4047364d83c2a783a3f077f"`);
        await queryRunner.query(`ALTER TABLE "product" DROP CONSTRAINT "FK_0dce9bc93c2d2c399982d04bef1"`);
        await queryRunner.query(`ALTER TABLE "category" DROP CONSTRAINT "FK_dc252738f70366595ac88f5a98f"`);
        await queryRunner.query(`ALTER TABLE "store_admin" DROP CONSTRAINT "FK_2b5e671b4f35cf8607999a45858"`);
        await queryRunner.query(`ALTER TABLE "store_admin" DROP CONSTRAINT "FK_718d4f5da12f0c830e6029a8b23"`);
        await queryRunner.query(`ALTER TABLE "store" DROP CONSTRAINT "FK_f3eb3afc763da3076e80e2459dd"`);
        await queryRunner.query(`ALTER TABLE "store" DROP CONSTRAINT "FK_36605697bf2bb48490037ca84f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a4e465e0706f17aa08ebbf002"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6f6b3bf9a7a89c6c4cdee267c0"`);
        await queryRunner.query(`DROP TABLE "community_feed_image_file"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c9d92baba7161372d3d61546e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_68fa2627eaeda368f495765bb3"`);
        await queryRunner.query(`DROP TABLE "notification_users_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_223ffd0c23037df1f55ecb182a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a59b6d136c6e7eaf61f22f3f4"`);
        await queryRunner.query(`DROP TABLE "product_image_file"`);
        await queryRunner.query(`DROP TABLE "community_feed"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP TABLE "otp"`);
        await queryRunner.query(`DROP TABLE "search_history"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30e98e8746699fb9af235410af"`);
        await queryRunner.query(`DROP TABLE "session"`);
        await queryRunner.query(`DROP TABLE "testimonial"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e1f623798118e629b46a9e629"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0cd76a8cdee62eeff31d384b73"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TABLE "applicant_to_community"`);
        await queryRunner.query(`DROP TABLE "community"`);
        await queryRunner.query(`DROP TABLE "swap"`);
        await queryRunner.query(`DROP TABLE "applicant_to_swap"`);
        await queryRunner.query(`DROP TABLE "donation"`);
        await queryRunner.query(`DROP TABLE "applicant_to_donation"`);
        await queryRunner.query(`DROP TABLE "product"`);
        await queryRunner.query(`DROP TYPE "public"."product_type_enum"`);
        await queryRunner.query(`DROP TABLE "category"`);
        await queryRunner.query(`DROP TABLE "store_admin"`);
        await queryRunner.query(`DROP TABLE "store"`);
        await queryRunner.query(`DROP TABLE "address"`);
        await queryRunner.query(`DROP TABLE "file"`);
        await queryRunner.query(`DROP TABLE "status"`);
        await queryRunner.query(`DROP TABLE "role"`);
    }

}
