services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: linkbook-postgres
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - linkbook-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    env_file:
      - ./.local.env


  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    container_name: linkbook-adminer
    restart: always
    ports:
      - 8082:8080

volumes:
  linkbook-db: