services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: postgres
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - skaner-db:/var/lib/postgresql/data
      - ./multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: ${DATABASE_NAME}, ${DATABASE_TEST_NAME}

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    container_name: mailer
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8085:8080

networks:
  observability:
    name: observability

volumes:
 skaner-db:
