volumes:
  linkbook-db-prod:
  uploads:

services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    container_name: linkbook-postgres-prod
    ports:
      - 5434:5432
    volumes:
      - linkbook-db-prod:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - linkbookServerNetwork
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - traefikNetwork
      - linkbookServerNetwork
  adminer:
    image: adminer
    container_name: linkbook-adminer-prod
    restart: always
    ports:
      - 8082:8080
    networks:
      - traefikNetwork
      - linkbookServerNetwork
  backend:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: linkbook-server
    ports:
      - ${APP_PORT}:4001
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:secret@postgres:5432/linkbook-db-prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.linkbookbackend.rule=Host(`backend.linkbook.store`)"
      - "traefik.http.routers.linkbookbackend.entrypoints=websecure"
      - "traefik.http.routers.linkbookbackend.tls=true"
      - "traefik.http.routers.linkbookbackend.tls.certresolver=le"
      - "traefik.http.routers.linkbookbackend.tls.domains[0].main=backend.linkbook.store"
      - "traefik.http.middlewares.linkbookbackend-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.linkbookbackend.middlewares=linkbookbackend-redirect"
    networks:
      - traefikNetwork
      - linkbookServerNetwork
    volumes:
      - uploads:/app/uploads
      - "~/shared_vps/traefik/certs:/letsencrypt"
networks:
  traefikNetwork:
    external: true
  linkbookServerNetwork:
    internal: true