export const brands = [
  { brand: 'Adidas', model: 'Samba OG', reference_number: 'B75806' },
  { brand: 'Adidas', model: 'Questar Flow', reference_number: 'EE8221' },
  { brand: 'Adidas', model: 'Stan Smith', reference_number: 'M20324' },
  { brand: 'Adidas', model: 'RapidaRun', reference_number: 'AC8295' },
  { brand: 'Adidas', model: 'Terrex Agravic TR', reference_number: 'BC0516' },
  { brand: 'Adidas', model: 'Superstar', reference_number: 'EG4958' },
  { brand: 'Adidas', model: 'Nizza Pride', reference_number: 'EF2318' },
  { brand: 'Adidas', model: 'SL 72', reference_number: 'FW1416' },
  { brand: 'Adidas', model: 'Matchbreak Super', reference_number: 'FX2708' },
  { brand: 'Adidas', model: 'Zurro SPZL', reference_number: 'FZ1603' },
  { brand: 'Adidas', model: 'Predator 20.3 FG', reference_number: 'EF1645' },
  { brand: 'Adidas', model: 'D Rose 10 Pride', reference_number: 'EH2455' },
  { brand: 'Adidas', model: 'Copa 20.3 Turf', reference_number: 'EF1943' },
  {
    brand: 'Adidas',
    model: 'Adizero Adios Boost 2',
    reference_number: 'S78010',
  },
  {
    brand: 'Adidas',
    model: 'Adizero Boston Boost 5',
    reference_number: 'B22870',
  },
  {
    brand: 'Adidas',
    model: 'Adizero Feather Prime',
    reference_number: 'S74427',
  },
  {
    brand: 'Adidas',
    model: 'Adizero Takumi Ren Boost 3',
    reference_number: 'BB6415',
  },
  { brand: 'Adidas', model: 'Duramo 6', reference_number: 'G64768' },
  { brand: 'Adidas', model: 'Energy Boost ESM', reference_number: 'B27132' },
  { brand: 'Adidas', model: 'Kanadia 7', reference_number: 'B40544' },
  {
    brand: 'Adidas',
    model: 'Questar Boost Techfit',
    reference_number: 'D66488',
  },
  { brand: 'Adidas', model: 'Response Boost', reference_number: 'M29706' },
  { brand: 'Adidas', model: 'Yeezy Boost', reference_number: 'BB5350' },
  { brand: 'Adidas', model: 'AlphaBounce', reference_number: 'BA8143' },
  { brand: 'Adidas', model: 'Harden Vol. 4', reference_number: 'EH2224' },
  { brand: 'Adidas', model: 'EQT Support', reference_number: 'BB1234' },
  { brand: 'Adidas', model: 'Dame 6', reference_number: 'EH2073' },
  { brand: 'Adidas', model: 'D.O.N. Issue #2', reference_number: 'FW8515' },
  { brand: 'Adidas', model: 'Harden Vol. 5', reference_number: 'FZ1071' },
  { brand: 'Adidas', model: 'T-Mac Millennium', reference_number: 'EF9844' },
  { brand: 'Adidas', model: 'Pro Boost Low', reference_number: 'EH2456' },
  { brand: 'Adidas', model: 'Hoops 3.0', reference_number: 'GY5432' },
  { brand: 'Adidas', model: 'Hoops 2.0', reference_number: 'FY8626' },
  { brand: 'Adidas', model: 'NMD_R1', reference_number: 'FX4350' },
  { brand: 'Adidas', model: 'Ultraboost 21', reference_number: 'FY0377' },
  { brand: 'Adidas', model: 'ZX 2K Boost', reference_number: 'FX8835' },
  { brand: 'Adidas', model: '4D Fusio', reference_number: 'FY3602' },
  { brand: 'Adidas', model: 'Forum Low', reference_number: 'FY7756' },
  { brand: 'Adidas', model: 'Superstar Vegan', reference_number: 'FW2295' },
  { brand: 'Adidas', model: 'Yeezy Foam Runner', reference_number: 'GV7903' },
  {
    brand: 'Adidas',
    model: 'Terrex Free Hiker Primeblue',
    reference_number: 'FX9255',
  },
  { brand: 'Adidas', model: 'Predator Freak.1', reference_number: 'FW7328' },
  { brand: 'Adidas', model: 'FYW XTA', reference_number: 'FX9153' },
  // Nike Brands
  { brand: 'Nike', model: 'Air Max 1', reference_number: 'FD9082' },
  { brand: 'Nike', model: 'Air Max 90', reference_number: 'CW7483' },
  { brand: 'Nike', model: "Air Force 1 '07", reference_number: '315122' },
  {
    brand: 'Nike',
    model: 'Air Jordan 1 Retro High OG',
    reference_number: '555088',
  },
  {
    brand: 'Nike',
    model: 'React Infinity Run Flyknit',
    reference_number: 'CD4371',
  },
  {
    brand: 'Nike',
    model: "Blazer Mid '77 Vintage",
    reference_number: 'BQ6806',
  },
  { brand: 'Nike', model: 'ZoomX Vaporfly NEXT%', reference_number: 'AO4568' },
  { brand: 'Nike', model: 'Dunk Low', reference_number: 'DD1391' },
  { brand: 'Nike', model: 'Metcon 6', reference_number: 'CT1241' },
  { brand: 'Nike', model: 'Pegasus Trail 3', reference_number: 'DA8697' },
  { brand: 'Nike', model: 'SB Dunk Low Pro', reference_number: 'BQ6817' },
  {
    brand: 'Nike',
    model: 'Air Zoom Alphafly NEXT%',
    reference_number: 'CI9925',
  },
  { brand: 'Nike', model: 'Air Max 270 React', reference_number: 'CT1264' },
  { brand: 'Nike', model: 'Air Zoom Tempo NEXT%', reference_number: 'CI9923' },
  { brand: 'Nike', model: 'Air Zoom Pegasus 37', reference_number: 'BQ9646' },
  { brand: 'Nike', model: 'Space Hippie 01', reference_number: 'CJ1646' },
  { brand: 'Nike', model: 'Air Jordan 5 Retro', reference_number: 'CT4838' },
  { brand: 'Nike', model: 'Air Max 2090', reference_number: 'BV9977' },
  { brand: 'Nike', model: 'React Vision', reference_number: 'CD4373' },
  { brand: 'Nike', model: 'Air Jordan 3 Retro', reference_number: 'CT8532' },
  { brand: 'Nike', model: 'SB Dunk High Pro', reference_number: 'CZ8149' },
  { brand: 'Nike', model: 'LeBron 18', reference_number: 'CQ9283' },
  { brand: 'Nike', model: 'Kyrie 7', reference_number: 'CQ9327' },
  {
    brand: 'Nike',
    model: 'Mercurial Vapor 14 Elite FG',
    reference_number: 'CV0993',
  },
  {
    brand: 'Nike',
    model: 'Tiempo Legend 9 Elite FG',
    reference_number: 'CZ8482',
  },
  { brand: 'Nike', model: 'Phantom GT Elite FG', reference_number: 'CK8439' },
  { brand: 'Nike', model: 'Waffle One', reference_number: 'DA7995' },
  { brand: 'Nike', model: 'Air Huarache', reference_number: 'DD1068' },
  { brand: 'Nike', model: 'Cortez Basic Leather', reference_number: '819719' },
  { brand: 'Nike', model: 'Air Max Pre-Day', reference_number: 'DD0338' },
  // Puma Brands
  { brand: 'Puma', model: 'Suede Classic', reference_number: '352634' },
  { brand: 'Puma', model: 'RS-X', reference_number: '369579' },
  { brand: 'Puma', model: 'Cali', reference_number: '369155' },
  { brand: 'Puma', model: 'Future Rider', reference_number: '371149' },
  { brand: 'Puma', model: 'LQDCell Optic', reference_number: '192560' },
  { brand: 'Puma', model: 'Cell Alien OG', reference_number: '369801' },
  { brand: 'Puma', model: 'Thunder Spectra', reference_number: '367516' },
  { brand: 'Puma', model: 'Ralph Sampson Lo', reference_number: '370847' },
  { brand: 'Puma', model: 'Basket Classic', reference_number: '354367' },
  { brand: 'Puma', model: 'Ignite Limitless', reference_number: '189987' },
  { brand: 'Puma', model: 'Calibrate Runner', reference_number: '193698' },
  { brand: 'Puma', model: 'Future Z 1.1', reference_number: '106028' },
  { brand: 'Puma', model: 'Ultra 1.1', reference_number: '106044' },
  { brand: 'Puma', model: 'RS-Dreamer', reference_number: '193990' },
  { brand: 'Puma', model: 'Mirage Mox', reference_number: '375167' },
  { brand: 'Puma', model: 'RS-Fast', reference_number: '380562' },
  { brand: 'Puma', model: 'Wild Rider', reference_number: '381517' },
  { brand: 'Puma', model: 'Fuse', reference_number: '194419' },
  { brand: 'Puma', model: 'Deviate Nitro', reference_number: '194441' },
  { brand: 'Puma', model: 'Magnify Nitro', reference_number: '195171' },
  { brand: 'Puma', model: 'Eternity Nitro', reference_number: '195102' },
  { brand: 'Puma', model: 'Liberate Nitro', reference_number: '195065' },
  { brand: 'Puma', model: 'Velocity Nitro', reference_number: '194598' },
  { brand: 'Puma', model: 'Spectra', reference_number: '195233' },
  { brand: 'Puma', model: 'Oslo-City', reference_number: '380743' },
  // Reebok Brands
  { brand: 'Reebok', model: 'Club C 85', reference_number: 'AR0456' },
  { brand: 'Reebok', model: 'Classic Leather', reference_number: '49799' },
  { brand: 'Reebok', model: 'Nano 9', reference_number: 'DV6343' },
  { brand: 'Reebok', model: 'Floatride Run', reference_number: 'CN2592' },
  { brand: 'Reebok', model: 'Instapump Fury', reference_number: 'V47514' },
  { brand: 'Reebok', model: 'Zig Kinetica', reference_number: 'EH1721' },
  { brand: 'Reebok', model: 'Question Mid', reference_number: 'EF7598' },
  { brand: 'Reebok', model: 'Sole Fury', reference_number: 'DV4486' },
  { brand: 'Reebok', model: 'Legacy Lifter', reference_number: 'CN1001' },
  { brand: 'Reebok', model: 'Aztrek 96', reference_number: 'DV6755' },
  { brand: 'Reebok', model: 'Nano X1', reference_number: 'H02868' },
  { brand: 'Reebok', model: 'Floatride Energy 3', reference_number: 'FY7756' },
  { brand: 'Reebok', model: 'Zig Dynamica', reference_number: 'H01256' },
  {
    brand: 'Reebok',
    model: 'Forever Floatride Energy 2',
    reference_number: 'DV6228',
  },
  { brand: 'Reebok', model: 'BB 4000 II', reference_number: 'GX0601' },
  { brand: 'Reebok', model: 'Club C Double', reference_number: 'FW7790' },
  {
    brand: 'Reebok',
    model: 'Reebok x Cardi B Club C',
    reference_number: 'FW8720',
  },
  { brand: 'Reebok', model: 'Answer V', reference_number: 'EF7602' },
  { brand: 'Reebok', model: 'DMX Trail Shadow', reference_number: 'DV9316' },
  { brand: 'Reebok', model: 'Classic Nylon', reference_number: 'CN7023' },
  { brand: 'Reebok', model: 'Royal Turbo Impulse', reference_number: 'DV6630' },
  { brand: 'Reebok', model: 'Legacy 83', reference_number: 'FX2588' },
  { brand: 'Reebok', model: 'Zig Kinetica II', reference_number: 'H67945' },
  { brand: 'Reebok', model: 'Instapump Fury Zone', reference_number: 'GZ5363' },
  { brand: 'Reebok', model: 'Premier Road Modern', reference_number: 'H01350' },
  {
    brand: 'Reebok',
    model: 'Reebok x Maison Margiela Tabi Instapump Fury',
    reference_number: 'FX1407',
  },
  {
    brand: 'Reebok',
    model: 'Reebok x Pyer Moss Experiment 4',
    reference_number: 'H01891',
  },
  { brand: 'Reebok', model: 'Club C Revenge', reference_number: 'FX1129' },
  { brand: 'Reebok', model: 'CL Legacy', reference_number: 'FY7557' },
  { brand: 'Reebok', model: 'Beatnik', reference_number: 'FY2949' },
  // New Balance
  { brand: 'New Balance', model: '327', reference_number: 'MS327' },
  { brand: 'New Balance', model: '550', reference_number: 'BB550' },
  { brand: 'New Balance', model: '990v5', reference_number: 'M990GL5' },
  { brand: 'New Balance', model: '992', reference_number: 'M992' },
  { brand: 'New Balance', model: '2002R', reference_number: 'M2002R' },
  { brand: 'New Balance', model: '1300', reference_number: 'M1300JP3' },
  { brand: 'New Balance', model: '1600', reference_number: 'CM1600' },
  { brand: 'New Balance', model: '1906R', reference_number: 'M1906R' },
  { brand: 'New Balance', model: '9060', reference_number: 'U9060' },
  { brand: 'New Balance', model: 'KAWHI', reference_number: 'BBKLS' },
  // Under Armour
  { brand: 'Under Armour', model: 'Curry 8', reference_number: '3023085' },
  { brand: 'Under Armour', model: 'HOVR Phantom', reference_number: '3021952' },
  {
    brand: 'Under Armour',
    model: 'Project Rock 3',
    reference_number: '3023004',
  },
  {
    brand: 'Under Armour',
    model: 'HOVR Summit Fat Tire',
    reference_number: '3022139',
  },
  { brand: 'Under Armour', model: 'UA Spawn 2', reference_number: '3022629' },
  // Asics
  { brand: 'ASICS', model: 'GEL-Kayano 26', reference_number: '1011A541' },
  { brand: 'ASICS', model: 'GEL-Nimbus 21', reference_number: '1011A169' },
  { brand: 'ASICS', model: 'GEL-Quantum 360 5', reference_number: '1021A105' },
  { brand: 'ASICS', model: 'METARUN', reference_number: 'T800N' },
  { brand: 'ASICS', model: 'GEL-Cumulus 20', reference_number: '1011A008' },
  // Converse
  { brand: 'Converse', model: 'Chuck 70', reference_number: '162050C' },
  { brand: 'Converse', model: 'One Star Pro', reference_number: '166024C' },
  { brand: 'Converse', model: 'Jack Purcell', reference_number: '163174C' },
  { brand: 'Converse', model: 'Pro Leather', reference_number: '168404C' },
  { brand: 'Converse', model: 'Run Star Hike', reference_number: '166799C' },
  // Vans
  { brand: 'Vans', model: 'Old Skool', reference_number: 'VN000D3HY28' },
  { brand: 'Vans', model: 'Sk8-Hi', reference_number: 'VN000D5IB8C' },
  { brand: 'Vans', model: 'Era', reference_number: 'VN000QFKBKA' },
  { brand: 'Vans', model: 'Authentic', reference_number: 'VN000EE3BLK' },
  { brand: 'Vans', model: 'Slip-On', reference_number: 'VN000EYEBWW' },
  // Jordan
  {
    brand: 'Jordan',
    model: 'Air Jordan 1 Retro High OG',
    reference_number: '555088-610',
  },
  {
    brand: 'Jordan',
    model: 'Air Jordan 4 Retro',
    reference_number: '308497-106',
  },
  {
    brand: 'Jordan',
    model: 'Air Jordan 11 Retro',
    reference_number: '378037-061',
  },
  {
    brand: 'Jordan',
    model: 'Air Jordan 3 Retro',
    reference_number: '854262-106',
  },
  {
    brand: 'Jordan',
    model: 'Air Jordan 5 Retro',
    reference_number: '136027-148',
  },
  // Gucci
  [
    {
      brand: 'Gucci',
      model: 'Gucci Tennis 1977',
      reference_number: '606110-HVK30-9761',
    },
    {
      brand: 'Gucci',
      model: 'GG Supreme Canvas Sneakers',
      reference_number: '669582-UPGA0-2348',
    },
    {
      brand: 'Gucci',
      model: 'Rhyton Leather Sneakers',
      reference_number: '579317-DRW00-9522',
    },
    {
      brand: 'Gucci',
      model: 'Ace GG Supreme Sneakers',
      reference_number: '550051-9N050-8465',
    },
    {
      brand: 'Gucci',
      model: 'Re-Web sneaker',
      reference_number: '786186-AADKA-9570',
    },
    {
      brand: 'Gucci',
      model: 'Gucci Basket Sneakers',
      reference_number: '661311-2SH80-9063',
    },
  ],
];

export const parts: { text: string }[] = [
  {
    text: 'input: if the image is sneaker or shoe, provide the brand, model, color, reference number and a small description about it that you found',
  },
  {
    text: 'output: JSON object organized as follows {brand: brand, model: model, color: color, reference_number: reference_number, description: description}, if the image include shoes or Sneaker',
  },
  {
    text: `input: check if shoes model and brand matches one of the following array of brands ${JSON.stringify(
      brands,
      null,
      2,
    )}, take the best match, otherwise return the brand and model that you found with small description about it`,
  },
  {
    text: 'output: JSON object organized as follows {brand: brand, model: model, color: color, reference_number: reference_number, description: description}',
  },
  {
    text: 'input: if the image does not include a shoe or sneaker, return what you have found in the image',
  },
  {
    text: 'output: if the image does not includes a shoes or sneaker, return JSON object organized as follows {brand: brand, model: model, color: color, reference_number: reference_number, description: description}',
  },
  { text: 'output: do not use ```json' },
];
